---
resources:
- name: git-teamfemr2-app
  type: git
  source:
    uri: https://github.com/kevinzurek/teamfemr2.git
    branch: master

- name: git-femr-app
  type: git
  source:
    uri: https://github.com/femr/femr.git
    branch: master

- name: git-concourse-app
  type: git
  source:
    uri: https://github.com/kevinzurek/teamfemr-concourse
    branch: master

- name: s3-config
  type: s3
  source:
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    bucket: git-femr-app
    versioned_file: femr.zip

jobs:
- name: deploy-TeamfEMR
  public: true
  plan:
  - get: git-concourse-app
  - get: git-teamfemr2-app
    trigger: true
  - task: teamfemr2-deploy
    file: git-concourse-app/teamfemr2/task_deploy.yml

- name: build-test-fEMR
  public: true
  plan:
  - get: git-concourse-app
  - get: git-femr-app
    trigger: true
  - task: femr-build
    file: git-concourse-app/femr/task_run_build.yml
  - task: femr-test
    file: git-concourse-app/femr/task_run_tests.yml
#- name: test-fEMR
#  public: true
#  plan:
#  - get: git-concourse-app
#  - get: git-femr-app
#    passed: [build-fEMR]
#    trigger: true
#  - task: femr-test
#    file: git-concourse-app/femr/task_run_tests.yml
- name: package-fEMR
  public: true
  plan:
  - get: git-concourse-app
  - get: git-femr-app
    passed: [build-test-fEMR]
    trigger: true
  - get: s3-config
  - task: femr-package
    file: git-concourse-app/femr/task_run_package.yml
  - put: s3-config
    params: {file: femr-dist/femr.zip}
- name: deploy-FEMR
  public: true
  plan:
  - get: git-concourse-app
  - get: s3-config
    passed: [package-fEMR]
  - get: git-femr-app
    passed: [package-fEMR]
    trigger: true
  - task: femr-deploy
    file: git-concourse-app/femr/task_run_deploy.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
